### ISSUE TITLE
enableAutoPipelining support?

### ISSUE THREAD

**Issue by Allain55** [jeffbski/redis-rstream#14]
Hi,

I've tried turning on enableAutoPipelining when creating a new Redis client but I get an error when using this client with redisRStream:
```
Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
    at new NodeError (node:internal/errors:329:5)
    at readableAddChunk (node:internal/streams/readable:276:30)
    at RedisRStream.Readable.push (node:internal/streams/readable:227:10)
    at getrangeCallback (%PROJECT%/node_modules/redis-rstream/lib/redis-rstream.js:56:16)
    at tryCatcher (%PROJECT%/node_modules/standard-as-callback/built/utils.js:11:23)
    at %PROJECT%/node_modules/standard-as-callback/built/index.js:19:49
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

Saw this with Redis 6.0.5 on AWS and v6.2.1 (Ubuntu 16.04.7)
Ioredis version: 4.23

**Comment by Allain55** [comment]
It works with the latest ioredis
